import { IProject } from "@/types"

export const projects: IProject[] = [
  {
    name: "SkiCalc.com",
    status: "Active",
    description: "Ski Size Calculator.",
    stack: ["next", "react", "typescript", "shadcn"],
    logo: "/skicalc.png",
    timePeriod: "April 2025 - now",
    urlText: "Go to website",
    url: "https://www.skicalc.com",
  },
  {
    name: "SkiCamps.org",
    status: "Active",
    description: "Directory for ski camps.",
    stack: ["next", "react", "typescript", "shadcn", "seo"],
    logo: "/skicamps.png",
    timePeriod: "April 2025 - now",
    urlText: "Go to website",
    url: "https://www.skicamps.org",
  },
  {
    name: "Virality Masters",
    status: "On hold",
    logo: "/viralitymasters.png",
    description: "Content mentorship platform.",
    stack: ["next", "react", "typescript", "shadcn", "supabase"],
    timePeriod: "March 2025 - April 2025",
    urlText: "Go to website",
    url: "https://www.viralitymasters.com",
  },
  {
    name: "Github City",
    status: "Discontinued",
    logo: "/github-city.png",
    description:
      "Watch your GitHub contributions transform into a bustling metropolis.",
    stack: ["three.js", "react", "typescript"],
    timePeriod: "One random evening",
    urlText: "Go to website",
    url: "https://github-city-82cf.vercel.app/",
  },
  {
    name: "Spots Guru",
    status: "Discontinued",
    description: "Storefront for travel creators.",
    logo: "/spotsguru.png",
    stack: [
      "next",
      "react",
      "typescript",
      "shadcn",
      "supabase",
      "resend",
      "stripe",
    ],
    timePeriod: "November 2024 - now",
    urlText: "Go to website",
    url: "https://spotsguru.com",
  },
  {
    name: "Memecoins.wtf",
    status: "Discontinued",
    logo: "/memecoins.png",
    description: "Memecoin tools directory.",
    stack: ["next", "react", "typescript", "shadcn"],
    timePeriod: "November 2024 - January 2025",
    urlText: "Go to website",
    url: "https://memecoins.wtf",
  },
  {
    name: "Juan Rallo Quotes",
    status: "Discontinued",
    logo: "/juanralloquotes.png",
    description: "Quotes from Juan Ramón Rallo.",
    stack: ["metricool", "twitter"],
    timePeriod: "2020 - now",
    mrr: 0,
    urlText: "View on Twitter",
    highlight: "+11k followers",
  },
  {
    name: "Juan Rallo AI",
    status: "Discontinued",
    logo: "/juanralloai.png",
    description: "Ask Juan Ramón Rallo.",
    stack: ["chatgpt"],
    timePeriod: "January 2024 - now",
    mrr: 0,
    urlText: "View on ChatGPT",
    url: "https://chat.openai.com/g/g-cLWRj9j9u-juan-ramon-rallo-ai",
    highlight: "+1k chats",
  },
  {
    name: "Citas Liberales",
    status: "Discontinued",
    logo: "/citasliberales.png",
    description: "Libertarian quotes in Spanish.",
    stack: ["metricool", "twitter"],
    timePeriod: "2020 - 2024",
    mrr: 0,
    highlight: "+3,7k followers",
  },
  {
    name: "CC0 Project",
    status: "Discontinued",
    logo: "/cc0.png",
    description: "Tokenized CC0 NFT community.",
    stack: ["solidity", "javascript"],
    timePeriod: "May 2022",
    urlText: "View on Etherscan",
    url: "https://etherscan.io/token/0xa73a6462AF0b63BcD249a9F9Bda588096A87A59B",
    highlight: "+50 holders",
  },
  {
    name: "Medieval Fantasy",
    status: "Discontinued",
    logo: "/medieval-fantasy.png",
    description: "Medieval-inspired HTML game.",
    stack: ["Javascript", "HTML", "Canva2D", "CSS"],
    timePeriod: "December 2020",
    urlText: "Play now!",
    url: "https://asierbayon.github.io/medieval-fantasy-game/index.html",
  },
  {
    name: "Hola DeFi",
    status: "Discontinued",
    logo: "/holadefi.png",
    description:
      "Spanish-speaking directory for decentralized finance applications.",
    stack: ["wordpress", "notion", "twitter", "canva"],
    timePeriod: "2020",
    highlight: "Revenue €600",
  },
  {
    name: "Liberbrand",
    status: "Discontinued",
    description: "Apparel for the Libertarian Market.",
    logo: "/liberbrand.png",
    stack: [
      "shopify",
      "printful",
      "notion",
      "canva",
      "twitter",
      "instagram",
      "facebook ads",
    ],
    mrr: 600,
    timePeriod: "Mid 2020 - Mid 2021",
    highlight: "€600 MRR",
  },
  {
    name: "Alfa Apuestas",
    status: "Discontinued",
    description: "Sports predictions service.",
    logo: "/alfaapuestas.png",
    stack: ["telegram", "twitter", "canva", "excel", "blogabet"],
    mrr: 1200,
    timePeriod: "2016 - 2017",
    highlight: "€1,2k MRR & 3k subscribers",
  },
  {
    name: "Galas Bilbao",
    status: "Discontinued",
    logo: "/galas-bilbao.png",
    description: "High-school graduation parties.",
    stack: ["instagram", "twitter", "word-of-mouth"],
    mrr: 5000,
    timePeriod: "2015 - 2017",
    highlight: "5k MRR (+8k tickets sold)",
  },
]
